openapi: 3.1.0
x-stoplight:
  id: hkixc05yjtrak
info:
  title: openapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/auth/register:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                      access_token:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: ok
                    data:
                      username: bob
                      access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2NGNlNjRhZjQxZWJhNDJmYjY3YWM2ZDgiLCJpYXQiOjE2OTEyNDc3OTEsImV4cCI6MTY5MTMzNDE5MX0.Z8FsWlBSnXqbLHs_jnfO4Q68ihbfakTHOIsdM2TDpQ0
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
        '':
          description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
              x-examples:
                Example 1:
                  email: bob.fellow@gmail.com
                  username: bob
                  first_name: Bob
                  last_name: Fellow
                  password: bob
            examples:
              Create User Bob Fellow:
                value:
                  first_name: Bob
                  username: Bob123
                  last_name: Fellow
                  email: bob.fellow@gmail.com
                  password: bob123
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  /v1/auth/login:
    post:
      summary: Login User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                      access_token:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: ok
                    data:
                      username: bob
                      access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2NGNlNjRhZjQxZWJhNDJmYjY3YWM2ZDgiLCJpYXQiOjE2OTEyNDc3OTEsImV4cCI6MTY5MTMzNDE5MX0.Z8FsWlBSnXqbLHs_jnfO4Q68ihbfakTHOIsdM2TDpQ0
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
        '':
          description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  /v1/profile/update:
    post:
      summary: Update User
      operationId: update-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                      access_token:
                        type: string
                x-examples:
                  Example 1:
                    status: true
                    message: ok
                    data:
                      username: bob
                      access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2NGNlNjRhZjQxZWJhNDJmYjY3YWM2ZDgiLCJpYXQiOjE2OTEyNDc3OTEsImV4cCI6MTY5MTMzNDE5MX0.Z8FsWlBSnXqbLHs_jnfO4Q68ihbfakTHOIsdM2TDpQ0
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
        '':
          description: ''
      description: Create a new user.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
